name: Start Tests
on: push


jobs:
  test_job:
    name: Compile Tests
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v2
     
      - name: Open Test Folder
        run: cd ./test
        
      - name: List files
        run: ls

      - name: Compile Test
        run: gcc -o test.out test/testMain.c test/CuTest.c src/csvreader.c test/suite.c
        
      - name: Run Test
        run: ./test.out
